development:
  adapter: postgresql
  encoding: unicode
  database: quoty_development
  pool: 5
  username: kinopyo
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: quoty_test
  pool: 5
  username: kinopyo
  password: